"""add promo_video_url to events

Revision ID: 5c8b87af0219
Revises: 956ea659d2be
Create Date: 2026-08-13 15:17:25.919548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8b87af0219'
down_revision: Union[str, Sequence[str], None] = '956ea659d2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('promo_video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'promo_video_url')
    # ### end Alembic commands ###
