"""reviews_and_ratings

Revision ID: 80fd837094a4
Revises: d27437f2f8af
Create Date: 2026-08-15 00:49:30.562347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80fd837094a4'
down_revision: Union[str, Sequence[str], None] = 'd27437f2f8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizer_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organizer_id', name='uq_organizer_rating_user_organizer')
    )
    op.create_index(op.f('ix_organizer_ratings_organizer_id'), 'organizer_ratings', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_organizer_ratings_user_id'), 'organizer_ratings', ['user_id'], unique=False)
    op.create_table('platform_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_platform_rating_user')
    )
    op.create_index(op.f('ix_platform_ratings_user_id'), 'platform_ratings', ['user_id'], unique=False)
    op.create_table('instructor_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'instructor_id', name='uq_instructor_rating_user_instructor')
    )
    op.create_index(op.f('ix_instructor_ratings_instructor_id'), 'instructor_ratings', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_instructor_ratings_user_id'), 'instructor_ratings', ['user_id'], unique=False)
    op.create_table('event_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('axis_content_uptodate', sa.Integer(), nullable=False),
    sa.Column('axis_instructor_mastery', sa.Integer(), nullable=False),
    sa.Column('axis_value_for_price', sa.Integer(), nullable=False),
    sa.Column('axis_experience_driven', sa.Integer(), nullable=False),
    sa.Column('overall_computed', sa.Float(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PUBLISHED', 'HIDDEN', name='reviewstatus'), nullable=False),
    sa.Column('hidden_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_event_review_user_event')
    )
    op.create_index(op.f('ix_event_reviews_event_id'), 'event_reviews', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_reviews_user_id'), 'event_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_reviews_user_id'), table_name='event_reviews')
    op.drop_index(op.f('ix_event_reviews_event_id'), table_name='event_reviews')
    op.drop_table('event_reviews')
    op.drop_index(op.f('ix_instructor_ratings_user_id'), table_name='instructor_ratings')
    op.drop_index(op.f('ix_instructor_ratings_instructor_id'), table_name='instructor_ratings')
    op.drop_table('instructor_ratings')
    op.drop_index(op.f('ix_platform_ratings_user_id'), table_name='platform_ratings')
    op.drop_table('platform_ratings')
    op.drop_index(op.f('ix_organizer_ratings_user_id'), table_name='organizer_ratings')
    op.drop_index(op.f('ix_organizer_ratings_organizer_id'), table_name='organizer_ratings')
    op.drop_table('organizer_ratings')
    # ### end Alembic commands ###
