"""add is_instant_registration to events

Revision ID: 8ff85f3c21fa
Revises: 77be36dfd469
Create Date: 2026-08-14 12:10:00.387590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff85f3c21fa'
down_revision: Union[str, Sequence[str], None] = '77be36dfd469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'events',
        sa.Column('is_instant_registration', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_instant_registration')
    # ### end Alembic commands ###
