"""kpi_daily_snapshot

Revision ID: ce839d60b434
Revises: e8c075066969
Create Date: 2026-08-18 20:58:21.032634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce839d60b434'
down_revision: Union[str, Sequence[str], None] = 'e8c075066969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_daily_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('dimensions_json', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'metric_name', 'dimensions_json', name='uq_kpi_daily_snapshot')
    )
    op.create_index(op.f('ix_kpi_daily_snapshot_metric_name'), 'kpi_daily_snapshot', ['metric_name'], unique=False)
    op.create_index(op.f('ix_kpi_daily_snapshot_snapshot_date'), 'kpi_daily_snapshot', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_daily_snapshot_snapshot_date'), table_name='kpi_daily_snapshot')
    op.drop_index(op.f('ix_kpi_daily_snapshot_metric_name'), table_name='kpi_daily_snapshot')
    op.drop_table('kpi_daily_snapshot')
    # ### end Alembic commands ###
