"""event_deleted_at

Revision ID: d27437f2f8af
Revises: f12505e8c94e
Create Date: 2026-08-14 17:00:20.123523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27437f2f8af'
down_revision: Union[str, Sequence[str], None] = 'f12505e8c94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'deleted_at')
    # ### end Alembic commands ###
